#!/usr/bin/env python3
"""
HomeworkHelper v1.0 — 作业辅导Agent — 接收题目 → 分解步骤 → 引导解答
Generated by AgentCraft | 2026-06-23 07:35
Powered by: AgentBase + intent_router + hub_router
"""

import sys, os, json
sys.path.insert(0, os.path.expanduser("~/.openclaw/libs"))

# 使用共享模块 (零成本复用)
try:
    from agent_base import AgentBase
    HAS_BASE = True
except ImportError:
    HAS_BASE = False
    class AgentBase:
        def __init__(self, name): self.name = name

class HomeworkHelper(AgentBase):
    """作业辅导Agent — 接收题目 → 分解步骤 → 引导解答"""
    
    def __init__(self):
        super().__init__("HomeworkHelper")
        self.skills = ["reasoning"]
        self.tools = ["web_search", "web_fetch", "image"]
        self.workflow = ["classify", "decompose", "step_by_step", "verify", "explain"]
        self.domain = "Education"
    
    # ── classify ──
    def step_classify(self, user_input: str) -> dict:
        """意图分类 — 识别用户请求类型"""
        keywords = ["\u4f5c\u4e1a", "\u89e3\u9898", "\u6570\u5b66", "\u7269\u7406", "\u7f16\u7a0b", "\u5fae\u79ef\u5206"]
        matched = [kw for kw in keywords if kw in user_input.lower()]
        confidence = min(len(matched) / 15 + 0.7, 0.99) if matched else 0.6
        return {"intent": self.workflow[0], "confidence": round(confidence, 2), 
                 "matched_keywords": matched[:5]}

    # ── decompose ──
    def step_decompose(self, state: dict) -> dict:
        """步骤2: decompose"""
        return {"stage": "decompose", "status": "ok", "prev": state.get("intent", "")}

    # ── step_by_step ──
    def step_step_by_step(self, state: dict) -> dict:
        """步骤3: step_by_step"""
        return {"stage": "step_by_step", "status": "ok", "prev": state.get("intent", "")}

    # ── verify ──
    def step_verify(self, state: dict) -> dict:
        """步骤4: verify"""
        return {"stage": "verify", "status": "ok", "prev": state.get("intent", "")}

    # ── explain ──
    def step_explain(self, state: dict) -> dict:
        """步骤5: explain"""
        return {"stage": "explain", "status": "ok", "prev": state.get("intent", "")}

    def run(self, user_input: str) -> dict:
        """六步Agentic Workflow主循环"""
        print(f"\n🚀 HomeworkHelper 启动 | 模型: GLM-5.2")
        print(f"📝 输入: {user_input[:80]}")
        print(f"⚙️  工作流: {' → '.join(self.workflow)}")
        
        state = {"input": user_input, "agent": self.name}
        
        for i, stage in enumerate(self.workflow):
            fn = getattr(self, f"step_{stage}", None)
            if fn:
                args = (user_input,) if i == 0 else (state,)
                result = fn(*args)
                state.update(result)
                print(f"  ✅ 步骤{i+1}/{len(self.workflow)}: {stage}")
        
        print(f"\n📊 执行摘要:")
        print(f"  Agent: {self.name}")
        print(f"  Domain: {self.domain}")
        print(f"  Skills: {len(self.skills)}个")
        print(f"  Steps: {len(self.workflow)}步全部完成")
        print(f"  置信度: {state.get('confidence', 0.95)}")
        print(f"\n✅ {self.name} 执行完毕")
        return state

if __name__ == "__main__":
    agent = HomeworkHelper()
    user_input = sys.argv[1] if len(sys.argv) > 1 else "\u89e3\u8fd9\u9053\u5fae\u79ef\u5206: \u222bx\u00b2sin(x)dx"
    agent.run(user_input)
