#!/usr/bin/env python3
"""
WeatherBot v1.0 — 天气查询Agent — 接收城市 → 查天气API → 格式化回复
Generated by AgentCraft | 2026-06-23 07:35
Powered by: AgentBase + intent_router + hub_router
"""

import sys, os, json
sys.path.insert(0, os.path.expanduser("~/.openclaw/libs"))

# 使用共享模块 (零成本复用)
try:
    from agent_base import AgentBase
    HAS_BASE = True
except ImportError:
    HAS_BASE = False
    class AgentBase:
        def __init__(self, name): self.name = name

class WeatherBot(AgentBase):
    """天气查询Agent — 接收城市 → 查天气API → 格式化回复"""
    
    def __init__(self):
        super().__init__("WeatherBot")
        self.skills = ["weather"]
        self.tools = ["web_search"]
        self.workflow = ["classify", "fetch_weather", "format_response"]
        self.domain = "Information"
    
    # ── classify ──
    def step_classify(self, user_input: str) -> dict:
        """意图分类 — 识别用户请求类型"""
        keywords = ["\u5929\u6c14", "\u6e29\u5ea6", "\u9884\u62a5", "\u4e0b\u96e8", "\u6674\u5929"]
        matched = [kw for kw in keywords if kw in user_input.lower()]
        confidence = min(len(matched) / 15 + 0.7, 0.99) if matched else 0.6
        return {"intent": self.workflow[0], "confidence": round(confidence, 2), 
                 "matched_keywords": matched[:5]}

    # ── fetch_weather ──
    def step_fetch_weather(self, state: dict) -> dict:
        """步骤2: fetch_weather"""
        return {"stage": "fetch_weather", "status": "ok", "prev": state.get("intent", "")}

    # ── format_response ──
    def step_format_response(self, state: dict) -> dict:
        """步骤3: format_response"""
        return {"stage": "format_response", "status": "ok", "prev": state.get("intent", "")}

    def run(self, user_input: str) -> dict:
        """六步Agentic Workflow主循环"""
        print(f"\n🚀 WeatherBot 启动 | 模型: GLM-5.2")
        print(f"📝 输入: {user_input[:80]}")
        print(f"⚙️  工作流: {' → '.join(self.workflow)}")
        
        state = {"input": user_input, "agent": self.name}
        
        for i, stage in enumerate(self.workflow):
            fn = getattr(self, f"step_{stage}", None)
            if fn:
                args = (user_input,) if i == 0 else (state,)
                result = fn(*args)
                state.update(result)
                print(f"  ✅ 步骤{i+1}/{len(self.workflow)}: {stage}")
        
        print(f"\n📊 执行摘要:")
        print(f"  Agent: {self.name}")
        print(f"  Domain: {self.domain}")
        print(f"  Skills: {len(self.skills)}个")
        print(f"  Steps: {len(self.workflow)}步全部完成")
        print(f"  置信度: {state.get('confidence', 0.95)}")
        print(f"\n✅ {self.name} 执行完毕")
        return state

if __name__ == "__main__":
    agent = WeatherBot()
    user_input = sys.argv[1] if len(sys.argv) > 1 else "\u5317\u4eac\u660e\u5929\u5929\u6c14\u600e\u4e48\u6837"
    agent.run(user_input)
